platform :ios, '11.0'

target 'Martinet_Example' do
  use_frameworks!
  pod 'Martinet', :path => '../'

  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  pod 'ObjectMapper'
  pod 'PromiseKit'

  target 'Martinet_Tests' do
    inherit! :search_paths
  end
end
